科技產業:
  科技新聞與趨勢:
    - techcrunch.com
    - theverge.com
    - wired.com
  資訊科技研究:
    - gartner.com
    - forrester.com
    - idc.com
  開源社群與技術:
    - stackoverflow.com
    - github.com
    - news.ycombinator.com
  企業雲平台:
    - aws.amazon.com
    - cloud.google.com
    - azure.microsoft.com

B2B_SaaS:
  SaaS_市場研究:
    - g2.com
    - capterra.com
    - trustradius.com
  CRM_行銷科技:
    - martech.org
    - chiefmartec.com
  B2B_客戶經營:
    - blog.hubspot.com
    - salesforce.com/blog

醫療健康:
  醫療研究機構:
    - pubmed.ncbi.nlm.nih.gov
    - nih.gov
    - cdc.gov
  健康趨勢:
    - healthline.com
    - webmd.com
    - verywellhealth.com
  醫美趨勢:
    - allure.com
    - realself.com
    - asjpub.com

房地產_建築:
  房市動態:
    - zillow.com
    - redfin.com
    - lvr.land.moi.gov.tw          # 內政部實價登錄
  室內設計:
    - dezeen.com
    - archdaily.com
    - houzz.com
  房地產商業觀點:
    - propertyguru.com
    - ura.gov.sg

觀光_交通_旅遊:
  旅遊觀察:
    - skift.com
    - travelweekly.com
    - wttc.org
  航空與交通:
    - iata.org
    - flightglobal.com
  地方觀光資訊:
    - travel.taiwan.net.tw
    - tripadvisor.com

教育_親子:
  線上學習市場:
    - classcentral.com
    - edsurge.com
    - coursera.org
    - udemy.com
  親子市場:
    - babycenter.com
    - whattoexpect.com
    - scholastic.com/parents

食品_飲料:
  食品趨勢:
    - mintel.com
    - foodnavigator.com
    - ift.org
  生鮮_通路分析:
    - igd.com
    - nielseniq.com
  消費者評論:
    - yelp.com
    - openrice.com

FMCG_美妝_電商產業:
  個人護理產品:
      - pg.com
      - headandshoulders.com  
      - consumer.reports.org
      - influenster.com

  零售與電商趨勢:
    - retaildive.com
    - emarketer.com
  美妝產業動態:
    - glossy.co
    - beautymatter.com
    - wwd.com
  網站流量分析:
    - similarweb.com
    - junglescout.com

消費者行為與心理分析:
  消費者研究:
    - nielseniq.com
    - kantar.com
    - gwi.com
  廣告_搜尋與購物意圖:
    - thinkwithgoogle.com
    - facebook.com/business/news/insights

綜合研究與趨勢:
  產業趨勢與白皮書:
    - mckinsey.com
    - bcg.com
    - bain.com
  產業統計與報告:
    - statista.com
    - oecd.org
    - worldbank.org
    - ibisworld.com
    - euromonitor.com
  企業財經與產業新聞:
    - bloomberg.com
    - economist.com
    - reuters.com
  政府_官方統計:
    - moea.gov.tw
